### ISSUE TITLE
an inquiry

### ISSUE THREAD

**Issue by Prismatika** [StableFluffy/bg3-ai-voicetoolkit#3]
Hi StableFluffy, thank you so much for this tool. Was wondering if there was a way to set a priority level when creating the pak file? Also, would this be compatible with extracting lines from the new party epilogue?

**Comment by StableFluffy** [comment]
i guess it's currently 25. you can change priority in last line of lob/mod_pak.py.

Since i played BG3 till patch 3 and got no time to play now, idk if it would work for Epilogue. If you have problem on that, increasing priority may works.
